server:
  port: 8080
spring:
  application:
    name: shopping-cart
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:shoppingDB;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: h2